---
output:
  pdf_document: default
  html_document: default
---

```{r include = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)
library(gt)
library(tidyr)
```

# _ DATA IMPORTATION _

##IMPORTING DATA
The following imports all the campaign finance data from the ballot question. 
```{r include = FALSE} 
setwd('~/Desktop/PID/Campaign_Finance_Data')

#Q2022
OpposeTaxHike <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question1/Coalition_to_Stop_the_Tax_Hike_Amendment.xlsx")

CoalitionforSocialJusticeFairShare <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question1/CoalitionforSocialJusticeFairShare.xlsx")

Fair_Share_Massachusetts <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question1/Fair_Share_Massachusetts.xlsx") 

`Committee For Competitive Dental Plans for Consumers` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question2/Committee For Competitive Dental Plans for Consumers.xlsx")
`Committee to Protect Access to Quality Dental Care` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question2/Committee_to_Protect_Access_to_Quality_Dental_Care.xlsx")

`Massachusetts Dental Care Providers for Better Dental Benefits` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question2/Massachusetts Dental Care Providers for Better Dental Benefits.xlsx")
`Committee on Dental Insurance Quality` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question2/Committee on Dental Insurance Quality.xlsx")

`21st_Century_Alcohol_Retail_Reform_Committee` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question3/21st_Century_Alcohol_Retail_Reform_Committee.xlsx")

`Fair_And_Secure_Massachusetts` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question4/Fair_And_Secure_Massachusetts.xlsx")

`Vote_YES_for_Work_and_Family_Mobility` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2022Data/Question4/Vote_YES_for_Work_and_Family_Mobility.xlsx")

#Q2020 

`Coalition_for_Safe_and_Secure_Data` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2020Data/Question1/Coalition_for_Safe_and_Secure_Data.xlsx")

`Massachusetts_Right_to_Repair_Committee` <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2020Data/Question1/Massachusetts_Right_to_Repair_Committee.xlsx")

No_Ranked_Choice_Voting_Committee_2020 <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2020Data/Question2/No_Ranked_Choice_Voting_Committee 2020.xlsx")

Ranked_Choice_Voting_2020_Committee <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2020Data/Question2/Ranked_Choice_Voting_2020_Committee.xlsx")

#Q2018 
Coalition_to_Protect_Patient_Safety <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2018Data/Question1/Coalition_to_Protect_Patient_Safety.xlsx")

Committee_to_Ensure_Safe_Patient_Care <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2018Data/Question1/Committee_to_Ensure_Safe_Patient_Care.xlsx")

People_Govern_Not_Money <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2018Data/Question2/People_Govern_Not_Money.xlsx")

Freedom_for_All_Massachusetts_Inc <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2018Data/Question3/Freedom_for_All_Massachusetts_Inc.xlsx")

Keep_Massachusetts_Safe <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2018Data/Question3/Keep_Massachusetts_Safe.xlsx")

No_to_3 <- read_xlsx("~/Desktop/PID/Campaign_Finance_Data/BallotQuestions2018Data/Question3/No_to_3.xlsx")
```

##CREATING LIST
```{r include = FALSE} 
Q2022 <- list(OpposeTaxHike, CoalitionforSocialJusticeFairShare, Fair_Share_Massachusetts, `Massachusetts Dental Care Providers for Better Dental Benefits`, `Committee For Competitive Dental Plans for Consumers`, `Committee on Dental Insurance Quality`, `Committee to Protect Access to Quality Dental Care`, `21st_Century_Alcohol_Retail_Reform_Committee`, `Fair_And_Secure_Massachusetts`, Vote_YES_for_Work_and_Family_Mobility)

Q2020 <- list(Coalition_for_Safe_and_Secure_Data, Massachusetts_Right_to_Repair_Committee, No_Ranked_Choice_Voting_Committee_2020, Ranked_Choice_Voting_2020_Committee)

Q2018 <- list(Coalition_to_Protect_Patient_Safety, Committee_to_Ensure_Safe_Patient_Care, People_Govern_Not_Money, Freedom_for_All_Massachusetts_Inc, Keep_Massachusetts_Safe, No_to_3)
```

##DATA WRANGLING
```{r }
Q2022 <- lapply(Q2022, function(df) {
  df %>% filter(Contributor != "Aggregated Unitemized Receipts")
})

Q2020 <- lapply(Q2020, function(df) {
  df %>% filter(Contributor != "Aggregated Unitemized Receipts")
})

Q2018 <- lapply(Q2018, function(df) {
  df %>% filter(Contributor != "Aggregated Unitemized Receipts")
})
```

#Names of Q2022
```{r}
Q2022 <- list(
"Coalition to Stop the Tax Hike Amendment (Q1 2022, Oppose)" = OpposeTaxHike, 

"Coalition for Social Justice Fair Share (Q1 2022, Support)" = CoalitionforSocialJusticeFairShare, 

"Fair Share Massachusetts (Q1 2022, Support)" = `Fair_Share_Massachusetts`, 

"Massachusetts Dental Care Providers for Better Dental Benefits (Q2 2022, Support)" = `Massachusetts Dental Care Providers for Better Dental Benefits`,

"Committee For Competitive Dental Plans for Consumers (Q2 2022, Oppose)" = `Committee For Competitive Dental Plans for Consumers`, 

"Committee on Dental Insurance Quality (Q2 2022, Support)" = `Committee on Dental Insurance Quality`, 

"Committee to Protect Access to Quality Dental Care (Q2 2022, Oppose)" = `Committee to Protect Access to Quality Dental Care`,

"21st Century Alcohol Retail Reform Committee (Q3 2022, Support)" = `21st_Century_Alcohol_Retail_Reform_Committee`,

"Fair And Secure Massachusetts (Q4 2022, Oppose)" = `Fair_And_Secure_Massachusetts`,

"Vote YES for Work and Family Mobility (Q4 2022, Support)" = `Vote_YES_for_Work_and_Family_Mobility`
)
```

#Names of Q2020
```{r} 
Q2020 <- list(

"Massachusetts Right to Repair Committee (Q1 2020,Support)" = 	Massachusetts_Right_to_Repair_Committee,

"Coalition for Safe and Secure Data (Q1 2020, Oppose)" = Coalition_for_Safe_and_Secure_Data,

"Ranked Choice Voting 2020 Committee (Q2 2020, Support)" = Ranked_Choice_Voting_2020_Committee,

"No Ranked Choice Voting Committee 2020 (Q2 2022, Oppose)" = No_Ranked_Choice_Voting_Committee_2020
)
```


#Name of Q2018
```{r} 
Q2018 <- list(
  
"Committee to Ensure Safe Patient Care (Q1 2018, Support)" = Committee_to_Ensure_Safe_Patient_Care, 

"Coalition to Protect Patient Safety (Q1 2018, Oppose)" = Coalition_to_Protect_Patient_Safety, 

"People Govern, Not Money (Q2 2018, Support)" = People_Govern_Not_Money,

"Freedom for All Massachusetts, Inc (Q3 2018, Support)" = Freedom_for_All_Massachusetts_Inc,

"No to 3 (Q3 2018, Oppose)" = No_to_3, 

"Keep Massachusetts Safe (Q3 2018, Oppose)" = Keep_Massachusetts_Safe
)
```

```{r}
combined_data <- c(Q2022, Q2020, Q2018)

combined_data <- lapply(names(combined_data), function(name) {
  df <- combined_data[[name]]
  year <- str_extract(name, "\\d{4}")
  question <- str_extract(name, "(?<=\\()[^\\)]+(?=,)")
  
  df$Year <- year
  df$Question <- question
  
  return(df)
})
```

```{r} 
combined_campaign_data <- bind_rows(combined_data)

combined_campaign_data <- combined_campaign_data |> mutate(Category_PID = case_when(
      `Record Type Description` == "Corporate Inkind Contribution" ~ "Corporate", 
      `Record Type Description` == "Business Contribution" ~ "Corporate", 
      `Record Type Description` == "Union/Association" ~ "Union/Association",
      `Record Type Description` == "Individual" & Amount >= 100000 ~ "Individual More Than 100K", 
      `Record Type Description` == "Individual" & Amount < 100000 ~ "Individual Less Than 100K",
      `Record Type Description` == "Committee" ~ "PAC", 
      `Record Type Description` == "Non-Contribution" ~ "Refund",
      `Record Type Description` == "Corporate Loan Forgiveness" ~ "Corporate Loan Forgiveness"
      ))

combined_campaign_data <- combined_campaign_data |> filter(`Record Type Description` != "Aggregated Unitemized Receipts")

combined_campaign_data <- combined_campaign_data |> filter(`Record Type Description` != "Aggregated Unitemized Inkind Contributions")

combined_campaign_data <- combined_campaign_data |> filter(`Record Type Description` != "Bank Interest")
```

```{r}
corporate_contributions <- combined_campaign_data |> filter(Category_PID %in% c("Corporate", "Corporate Loan Forgiveness"))

corporate_contributions

write.csv(corporate_contributions, file = "corporate_contributions.csv")
write.csv(combined_campaign_data, file = "combined_campaign_data.csv")
```

